### ISSUE TITLE
Add touchpoint id as label to issue

### ISSUE THREAD

**Issue by cheeragpatel** [jmassardo/issues-to-totango#10]
Add function to store touchpoint ID as label to issue for future updates of issues and touchpoints.

**Comment by rockin-robinson** [comment]
Instead of adding the id as a label, what if we have the actions bot add it as a comment on issue creation? We could put something like "event_id: 938274982194373918742" (or whatever the id is) and then when we need to edit the issue, we could just parse the comments for "event_id" and grab it.
