### ISSUE TITLE
What happens if the assignee is not a Hubber? Should we drop them? Should we specify the CSA/M and use that as the assignee?

### ISSUE THREAD

**Issue by jmassardo** [jmassardo/issues-to-totango#18]

**Comment by sam1el** [comment]
My vote would be for the CSA/M route. Unless there there someone like mark at microsoft with crazy access

**Comment by jmassardo** [comment]
We could specify the target assignee via a repo secret similar to the `ACCOUNT_ID`.
The `assignee` field in Totango only supports a single individual so we'd have to make a decision on which role would own that bit.

We could cal it `TOTANGO_ASSIGNEE_USERNAME`, boring but descriptive.

**Comment by sam1el** [comment]
I'd be okay with that. This is the one that correlates to the participantList in the API here correct? [participantList](https://support.totango.com/hc/en-us/articles/115000597266-Touchpoints-API#h_01FSHGQR8835PQWKGQGM8ATJ8Y)

**Comment by rockin-robinson** [comment]
https://github.com/jmassardo/issues-to-totango/blob/version2.0/index.js#L109
