### ISSUE TITLE
Discuss touchpoint and task creation. Both, or one/the other.

### ISSUE THREAD

**Issue by rockin-robinson** [jmassardo/issues-to-totango#47]

**Comment by collinmcneese** [comment]
https://github.com/jmassardo/issues-to-totango/blob/aeb1cf69cc158c84f8878bb6406faa86e976daae/index.js#L44
So for this, it is always creating a touchpoint -- perhaps we change the logic to only create a touchpoint if there is a touchpoint label?

**Comment by rockin-robinson** [comment]
Yes, exactly! :D I created an issue for this #49
